---
- hosts: all
  tasks:
    - name: Install postgres
      apt:
        name: ["postgresql", "python-psycopg2", "libpq-dev"]

    - name: Create piku postgres superuser
      become: true
      become_user: postgres
      postgresql_user:
        name: piku
        role_attr_flags: SUPERUSER
