name: Test Against OS Packages

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        distro: [ buster, jammy, focal ]

    steps:
    - uses: actions/checkout@v3
    - name: Test on ${{ matrix.distro }}
      run: |
        docker build .github/workflows/${{ matrix.distro }} -t local/${{ matrix.distro }}
        docker run -v "$PWD":/run local/${{ matrix.distro }}
