name: Test UV Deployment

on: [push, pull_request]

jobs:
  uv-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test UV deployment
      run: |
        docker build .github/workflows/uv-test -t local/uv-test
        docker run -v "$PWD":/run local/uv-test
